### ISSUE TITLE
Create a demo website which allows organize request from a user to admin

### ISSUE THREAD

**Issue by thealphadollar** [GirlScriptSummerOfCode/GirlScript_India#5] opened 2018-06-24 18:31 UTC
The is a crucial issue if you are serious about contributing to the creation of GirlScript India Website.

Using technologies you are comfortable with or preferable Django and already available tools, you are supposed to create a demo website. You can take inspiration from [DjangoGirls website](https://djangogirls.org/). It should be a barebone website, with at least the below pages and functionalities:

- Different hyperlinked pages such as home, contact, about, contribute etc.
- A method to make simple blog posts from the admin side.
- Subscribe method and other things you deem worth learning before starting the actual project.

"Organize request" feature:
- A form to accept entry and then populate a template with it. For eg., there could be a form to ask the name
- A user can click on organize request and fill that form, which is saved to the backend or google forms, etc
- Once admin approves the request, show a page with the name at URL `website.com/name`.

Since the elements of the website will be static, except the form and to populate a saved template, you can host it using GitHub pages and submit the link for evaluation.

The issue has been set up after much contemplation to make sure everyone learns in the best manner possible. We will be marking this issue as "topcoder" since it will require a lot of endeavours from your and our side too.

NOTE: Points will be given to everyone whose submissions are deemed appropriate. You've approximately the time till first evaluations since this is a huge learning task. 

All the best; please put in any doubts and clarifications in the thread.

**Give a thumbs up if you are working on the task.**

**Comment by mayankk98** [comment] 2018-06-24 18:32
👍🏻
Yes I am working on it

**Comment by devesh-verma** [comment] 2018-06-24 18:35
I am working on this too 😃

**Comment by mayankk98** [comment] 2018-06-24 18:38
I don't mean to put you down but this issue is exactly the same as I was
assigned and also as per first come first serve basis I think I should get
this assigned. I wouldn't mind ideas though

**Comment by thealphadollar** [comment] 2018-06-24 18:41
**"NOTE: Points will be given to everyone whose submissions are deemed appropriate. You've approximately the time till first evaluations since this is a huge learning task."**

@mayankk98

**Comment by mayankk98** [comment] 2018-06-24 18:45
So who is the issue assigned to, because:
1. As per the guidelines the issue is given based on first come first serve basis. 
2. Also, many people working on same issue can lead to time wastage.
3. I think this issue is similar to the issue "Using Bootsrap to Create a Template"

**Comment by mayankk98** [comment] 2018-06-24 18:47
I have already started working and will find it inconvenient if it's not considered. That's why I'm asking for clarification, that's all

**Comment by mayankk98** [comment] 2018-06-24 18:56
What is the difference between this issue and the issue "Use Bootstrap As a Template" ?

**Comment by darthgera123** [comment] 2018-06-24 18:56
can we do something
since this is a biggish project why dont we collaborate and come up with some mockups
also can you list out what all needs to be built

**Comment by thealphadollar** [comment] 2018-06-24 18:59
@mayankk98 

1. We have custom point allocation method for this since the website needs to be build from scratch and it's unlike other projects.
2. Everybody will get to learn the things required and hence I don't believe it's a time waste; **this is a learning issue**
3. The boot strap template will be used directly into the website; this is different since it requires to create a basic skeletal demo with roughly no content but functions.

**Comment by mayankk98** [comment] 2018-06-24 19:01
@thealphadollar 
Thanks a lot for the clarification. It was much needed

**Comment by thealphadollar** [comment] 2018-06-24 19:03
@darthgera123  I believe this isn't a really big thing to do in two weeks: just the basic functionality is to be created. If you still feel it's big, please ping me in personal and we will talk and come to a conclusion. I could be wrong since I'm not the one doing it :sweat_smile:

**Comment by Kushald2805** [comment] 2018-06-24 19:04
Even I wish to work on it. Thanks a lot for this issue as it will over all help us in developing.

**Comment by darthgera123** [comment] 2018-06-24 19:11
what i was thinking was that if we have to create a static website then we can simply use jekyll and bootstrap. we can use some existing themes in jekyll and even if we create our own its still simpler.

**Comment by aish51197** [comment] 2018-06-25 05:07
I want to work on this issue for frontend work and collaborating with @aditya81070  for backend  with Django.

**Comment by devshiva619** [comment] 2018-06-25 05:20
@mayankk98 he(@thealphadollar ) already mentioned clearly **Points will be given to everyone whose submissions are deemed appropriate.**.

**Comment by thealphadollar** [comment] 2018-06-25 08:54
@aish51197  Go forward :D

**Comment by shreyateeza** [comment] 2018-06-29 13:38
I am working on this issue! :)

**Comment by shreyateeza** [comment] 2018-06-29 13:40
@thealphadollar I can work with any tech stack, right? As is specified in the issue description-
> Using technologies you are comfortable with or preferable Django and already available tools

**Comment by vishwarajanand** [comment] 2018-06-29 14:21
@shreyateeza, your PR [for POC] would be accepted and points would be awarded as long as it fulfils the given objectives. Also, note that we are leaning towards using Django for our website. If you use it, it would be easier for us to integrate and you may get more points.

**Comment by shreyateeza** [comment] 2018-06-29 14:38
@vishwarajanand Thanks for the info! Will try to make the website using Django.

**Comment by vishwarajanand** [comment] 2018-07-07 13:55
Participants, please update your progress with this task.

**Comment by thealphadollar** [comment] 2018-07-17 16:07
In-progress by three participants.

We are continuing with the integration phase and anyone willing to work on this issue can do it for contribution and we will integrate his code if it's good enough in the improvement phase.

**Comment by vishwarajanand** [comment] 2018-09-02 15:43
Closing this issue, since the event is closed.

**Closed as completed by vishwarajanand** 2018-09-02 15:43 UTC
Labels: GSSoC, topcoder, Django, Demo, learning
